project_id = "hhtmqsgntrazmtoaxvis"

[functions.chat]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = true

[functions.send-receipt-email]
verify_jwt = true

[functions.mercury-sync]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.generate-estimate-pdf]
verify_jwt = true

[functions.generate-usta-form]
verify_jwt = true

[functions.send-usta-form]
verify_jwt = true

[functions.email-webhook]
verify_jwt = false

[functions.send-estimate-email]
verify_jwt = true

[functions.invite-team-member]
verify_jwt = true

[functions.reset-team-password]
verify_jwt = true

[functions.generate-receipt-pdf]
verify_jwt = true

[functions.notify-admin-action]
verify_jwt = true

[functions.submit-lead]
verify_jwt = false
