project_id = "hhtmqsgntrazmtoaxvis"

[functions.chat]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = true

[functions.send-receipt-email]
verify_jwt = true

[functions.mercury-sync]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.generate-usta-form]
verify_jwt = true

[functions.send-usta-form]
verify_jwt = true

[functions.email-webhook]
verify_jwt = false
