// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhtmqsgntrazmtoaxvis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodG1xc2dudHJhem10b2F4dmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExODExMzksImV4cCI6MjA3Njc1NzEzOX0.XNW93VY9zXF6RpNameIwOMUQDTNNKsHTjWeI9zn5b1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});